# Generated by Django 4.2.2 on 2023-06-25 05:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_contratacion', models.DateField()),
                ('numero_seguro_social', models.CharField(max_length=8)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cont_vacaciones', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('empleados', models.ManyToManyField(to='empleados.empleado')),
            ],
        ),
    ]
