# Generated by Django 4.1.3 on 2022-11-18 01:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('feriado', models.BooleanField(default=False)),
                ('septimo_dia', models.BooleanField(default=False)),
                ('vacaciones', models.BooleanField(default=False)),
                ('ausencia', models.BooleanField(default=False)),
                ('horas_extra', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('multa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
        ),
    ]
