# Generated by Django 4.2.2 on 2023-06-25 05:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('formula', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('feriado', models.BooleanField(default=False)),
                ('septimo_dia', models.BooleanField(default=False)),
                ('vacaciones', models.BooleanField(default=False)),
                ('ausencia', models.BooleanField(default=False)),
                ('horas_extra', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('multa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('vacaciones', models.BooleanField(default=False)),
                ('aguinaldo', models.BooleanField(default=False)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculos', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10), size=None)),
                ('totales', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10), size=None)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('formulas', models.ManyToManyField(to='nomina.formula')),
                ('jornadas', models.ManyToManyField(to='nomina.jornada')),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('vacaciones', models.BooleanField(default=False)),
                ('aguinaldo', models.BooleanField(default=False)),
                ('viaticos', models.BooleanField(default=False)),
                ('nominas', models.ManyToManyField(to='nomina.nomina')),
            ],
        ),
    ]
