# Generated by Django 4.1.3 on 2022-11-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_nomina_planilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='viaticos',
            field=models.BooleanField(default=False),
        ),
    ]
